# This file was generated by GoReleaser. DO NOT EDIT.
cask "templr" do
  name "templr"
  desc "A powerful Go template rendering CLI tool with Sprig functions"
  homepage "https://github.com/kanopi/templr"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "templr"

  on_macos do
    on_intel do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/kanopi/templr/"
      sha256 "8a53d0e977d6fdad835348c7f22c465b6f0efbc050fd67e7d2b4a111857999ce"
    end
    on_arm do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/kanopi/templr/"
      sha256 "f326e28d8b971331b4e83e057fcb6ec00715e6c62db9e503117d533f140ecc3f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr_#{version}_linux_amd64.tar.gz",
        verified: "github.com/kanopi/templr/"
      sha256 "c1edf40095347a5f9433a34ed2ecfc202fd7d9d400b8897cfcf71142a8f64c6a"
    end
    on_arm do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr_#{version}_linux_arm64.tar.gz",
        verified: "github.com/kanopi/templr/"
      sha256 "c00e95dc509377461efce519a3b6257966d59369075b84ce649ded3b91ae4909"
    end
  end

  # No zap stanza required
end
