# This file was generated by GoReleaser. DO NOT EDIT.
cask "templr" do
  name "templr"
  desc "A powerful Go template rendering CLI tool with Sprig functions"
  homepage "https://github.com/kanopi/templr"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "templr"

  on_macos do
    on_intel do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr-darwin-amd64",
        verified: "github.com/kanopi/templr/"
      sha256 "6ecbf62b59f02f25e7701ad7cb86f287ff54bc5f8d39ae636d20d96291c261f9"
    end
    on_arm do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr-darwin-arm64",
        verified: "github.com/kanopi/templr/"
      sha256 "667ff4d6a8d8cc999d534241c6b18974102af47a70d5efb7018b5c9856998c19"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr-linux-amd64",
        verified: "github.com/kanopi/templr/"
      sha256 "879f07994af63f5f654ff65033cb8d38a8a11e25876a058b36ed924fabb4f190"
    end
    on_arm do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr-linux-arm64",
        verified: "github.com/kanopi/templr/"
      sha256 "c450b927fec6364609aca405a5a7f1c5439316baabd6e14768b9427f65c4ae2f"
    end
  end

  # No zap stanza required
end
