# This file was generated by GoReleaser. DO NOT EDIT.
cask "templr" do
  name "templr"
  desc "A powerful Go template rendering CLI tool with Sprig functions"
  homepage "https://github.com/kanopi/templr"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "templr"

  on_macos do
    on_intel do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr-darwin-amd64.tar.gz",
        verified: "github.com/kanopi/templr/"
      sha256 "6de18310484f5ef7640d2013462942dc811e6f3a29be53938ea3a53b0ee49e41"
    end
    on_arm do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr-darwin-arm64.tar.gz",
        verified: "github.com/kanopi/templr/"
      sha256 "818385eb589fb4b83f2348f8de9bb57910a8bf717be3fe4b2662b44a53850e1a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr-linux-amd64.tar.gz",
        verified: "github.com/kanopi/templr/"
      sha256 "180098f4675de0cda29ed063b1628c6900b1f864a9e086ee5158983f31f8ffe1"
    end
    on_arm do
      url "https://github.com/kanopi/templr/releases/download/#{version}/templr-linux-arm64.tar.gz",
        verified: "github.com/kanopi/templr/"
      sha256 "7badce0fdce9aa2d28443cc352f5e03f4a7a9962c1ff5622456e36a4a127db8e"
    end
  end

  # No zap stanza required
end
